--/*
CREATE TABLE bosroul_user (
  bosroul_user_id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
  email varchar(320) NOT NULL,
  password varchar(60) NOT NULL,
  --oracle doens't have a boolean type, so admin_role:
  admin_role char(1) DEFAULT 'F' NOT NULL CHECK (admin_role in ('T','F')),
  registered_when timestamp NOT NULL,
  updated_when timestamp NOT NULL,
  CONSTRAINT bosroul_user_id_pkey PRIMARY KEY (bosroul_user_id)
);

CREATE TABLE suggestion (
  sugg_id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
  name varchar(20) NOT NULL,
  caption varchar(50) NOT NULL,
  date_end date ,
  made_when timestamp NOT NULL,
  bosroul_user_id number NOT NULL,
  CONSTRAINT sugg_id_pkey PRIMARY KEY (sugg_id),
  CONSTRAINT sugg_bosroul_user_id_fkey FOREIGN KEY (bosroul_user_id)
    REFERENCES bosroul_user(bosroul_user_id)
);

CREATE TABLE decides_on (
  dec_id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
  --oracle doens't have a domain specification, so decision:
  decision varchar(5) NOT NULL CHECK (decision in ('maybe','next')),
  decision_when timestamp NOT NULL,
  bosroul_user_id number NOT NULL,
  sugg_id number NOT NULL,
  CONSTRAINT dec_on_bosroul_user_id_fkey FOREIGN KEY (bosroul_user_id)
    REFERENCES bosroul_user(bosroul_user_id),
  CONSTRAINT decides_on_sugg_id_fkey FOREIGN KEY (sugg_id)
    REFERENCES suggestion(sugg_id)
);

CREATE TABLE tags (
  tag_id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
  word varchar(10) NOT NULL,
  tagged_when timestamp NOT NULL,
  bosroul_user_id number NOT NULL,
  sugg_id number NOT NULL,
  CONSTRAINT tags_bosroul_user_id_fkey FOREIGN KEY (bosroul_user_id)
    REFERENCES bosroul_user(bosroul_user_id),
  CONSTRAINT tags_sugg_id_fkey FOREIGN KEY (sugg_id)
    REFERENCES suggestion(sugg_id)
);

CREATE TABLE votes_on (
  vote_id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
  --oracle doens't have a domain specification, so vote:
  vote varchar(5) NOT NULL CHECK (vote in ('go','no')),
  voted_when timestamp NOT NULL,
  bosroul_user_id number NOT NULL,
  sugg_id number NOT NULL,
  CONSTRAINT votes_on_bosroul_user_id_fkey FOREIGN KEY (bosroul_user_id)
    REFERENCES bosroul_user(bosroul_user_id),
  CONSTRAINT votes_on_sugg_id_fkey FOREIGN KEY (sugg_id)
    REFERENCES suggestion(sugg_id)
);

--*/

/*
drop table votes_on;
drop table tags;
drop table decides_on;
drop table suggestion;
drop table bosroul_user;
--*/
/*
truncate table votes_on cascade;
truncate table tags cascade;
truncate table decides_on cascade;
truncate table suggestion cascade;
truncate table bosroul_user cascade;
--*/

