/******************************/
 /***   PHYSICAL DESIGN   ***/
/******************************/

--<< ORACLE CREATE TABLES >>--

CREATE TABLE BosroulUser (
  bosroul_user_id number GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  email varchar(320) NOT NULL UNIQUE,
  password varchar(60) NOT NULL,
  registered_when timestamp NOT NULL,
  updated_when timestamp NOT NULL
);

CREATE TABLE BosroulAdmin (
  admin_id number GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  bosroul_user_id number REFERENCES BosroulUser(bosroul_user_id)
);

CREATE TABLE Suggestion (
  sugg_id number GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  name varchar(20) NOT NULL,
  caption varchar(50) NOT NULL,
  date_end date ,
  made_when timestamp NOT NULL,
  bosroul_user_id number REFERENCES BosroulUser(bosroul_user_id)
);

CREATE TABLE DecidesOn (
  dec_id number GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  --oracle doesn't have a domain specification, so decision:
  decision varchar(5) NOT NULL CHECK (decision in ('maybe','next')),
  decided_when timestamp NOT NULL,
  bosroul_user_id number REFERENCES BosroulUser(bosroul_user_id),
  sugg_id number REFERENCES Suggestion(sugg_id)
);

CREATE TABLE Tags (
  tag_id number GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  word varchar(10) NOT NULL,
  tagged_when timestamp NOT NULL,
  bosroul_user_id number REFERENCES BosroulUser(bosroul_user_id),
  sugg_id number REFERENCES Suggestion(sugg_id),
  CONSTRAINT LMTTagsPerSuggToOnePerUser UNIQUE (bosroul_user_id,sugg_id)
);

CREATE TABLE VotesOn (
  vote_id number GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  --oracle doesn't have a domain specification, so vote:
  vote varchar(5) NOT NULL CHECK (vote in ('go','no')),
  voted_when timestamp NOT NULL,
  bosroul_user_id number REFERENCES BosroulUser(bosroul_user_id),
  sugg_id number REFERENCES Suggestion(sugg_id),
  CONSTRAINT LMTVotesPerSuggToOnePerUser UNIQUE (bosroul_user_id,sugg_id)
);


